export const Items = [
  {
    id: 1,
    name: "Himalaya Baby Wipes",
    category: "Baby Care",
    mrp: 48,
    sellingPrice: 32,
    image: "https://m.media-amazon.com/images/I/81z17LGBI+L._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 2,
    name: "Himalaya Aloe Vera Wipes",
    category: "Baby Care",
    mrp: 50,
    sellingPrice: 40,
    image: "https://m.media-amazon.com/images/I/81z17LGBI+L._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 3,
    name: "Himalaya Baby Soap",
    category: "Baby Care",
    mrp: 68,
    sellingPrice: 46,
    image:
      "https://m.media-amazon.com/images/I/61YFLf-Z0cL._AC_UL480_FMwebp_QL65_.jpg",
    quantity: 1,
  },
  {
    id: 4,
    name: "Himalaya Baby Massage Oil",
    category: "Baby Care",
    mrp: 120,
    sellingPrice: 81,
    quantity: 1,
  },
  {
    id: 5,
    name: "Himalaya Baby Powder",
    category: "Baby Care",
    mrp: 60,
    sellingPrice: 40,
    quantity: 1,
  },
  {
    id: 6,
    name: "Himalaya Lip Balm (20x18)",
    category: "Skin Care",
    mrp: 20,
    sellingPrice: 16,
    quantity: 1,
  },
  {
    id: 7,
    name: "Himalaya Anti-Dandruff Shampoo",
    category: "Hair Care",
    mrp: 175,
    sellingPrice: 131,
    quantity: 1,
  },
  {
    id: 8,
    name: "Himalaya Scrub Walnut (Satchet)",
    category: "Skin Care",
    mrp: 10,
    sellingPrice: 7.5,
    quantity: 1,
  },
  {
    id: 9,
    name: "Himalaya Neem Facewash",
    category: "Skin Care",
    mrp: 85,
    sellingPrice: 60,
    quantity: 1,
  },
  {
    id: 10,
    name: "Himalaya Facewash Lemon Oil",
    category: "Skin Care",
    mrp: 80,
    sellingPrice: 65,
    quantity: 1,
  },
  {
    id: 11,
    name: "Himalaya Kesar Facewash",
    category: "Skin Care",
    mrp: 90,
    sellingPrice: 74,
    quantity: 1,
  },
  {
    id: 12,
    name: "Himalaya Dark Spot Cream",
    category: "Skin Care",
    mrp: 95,
    sellingPrice: 78,
    quantity: 1,
  },
  {
    id: 13,
    name: "Himalaya Night Cream",
    category: "Skin Care",
    mrp: 270,
    sellingPrice: 189,
    quantity: 1,
  },
  {
    id: 14,
    name: "Himalaya Baby Hair Oil",
    category: "Baby Care",
    mrp: null,
    sellingPrice: null,
    quantity: 1,
  },
  {
    id: 15,
    name: "Himalaya Sparkling White Toothpaste",
    category: "Oral Care",
    mrp: null,
    sellingPrice: null,
    quantity: 1,
  },
  {
    id: 16,
    name: "Himalaya Complete Strong Toothpaste",
    category: "Oral Care",
    mrp: null,
    sellingPrice: null,
    quantity: 1,
  },
  {
    id: 17,
    name: "Mama Earth Face-Cream with Vit C",
    category: "Skin Care",
    mrp: 109,
    sellingPrice: 55,
    quantity: 1,
  },
  {
    id: 18,
    name: "Mama Earth Facewash Multani Mitti",
    category: "Skin Care",
    mrp: 125,
    sellingPrice: 63,
    quantity: 1,
  },
];
